project_id = "hmhxrjudggrzbbhnvvat"

[functions.admin-create-user]
verify_jwt = false

[functions.admin-delete-user]
verify_jwt = false

[functions.admin-update-user]
verify_jwt = false

[functions.chat-perplexity]
verify_jwt = false

[functions.analyze-image]
verify_jwt = false

[functions.parse-document]
verify_jwt = false