// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dmnrgpdpqgudqgrrlhjc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRtbnJncGRwcWd1ZHFncnJsaGpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ4MjYxMzIsImV4cCI6MjA5MDQwMjEzMn0.hzNvxq6RYsJ6S5coWglIumxlA9lYKy6kjGtJyqevwk4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});